// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pr-reviewer-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PRRepository is an autogenerated mock type for the PRRepository type
type PRRepository struct {
	mock.Mock
}

// CreateWithReviewers provides a mock function with given fields: ctx, pr, reviewerIDs
func (_m *PRRepository) CreateWithReviewers(ctx context.Context, pr *domain.PullRequest, reviewerIDs []string) error {
	ret := _m.Called(ctx, pr, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithReviewers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PullRequest, []string) error); ok {
		r0 = rf(ctx, pr, reviewerIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsPr provides a mock function with given fields: ctx, prID
func (_m *PRRepository) ExistsPr(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsPr")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, prID
func (_m *PRRepository) GetByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewers provides a mock function with given fields: ctx, prID
func (_m *PRRepository) GetReviewers(ctx context.Context, prID string) ([]string, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAssignedPRs provides a mock function with given fields: ctx, userID
func (_m *PRRepository) GetUserAssignedPRs(ctx context.Context, userID string) ([]*domain.PullRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAssignedPRs")
	}

	var r0 []*domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.PullRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.PullRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUserReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *PRRepository) IsUserReviewer(ctx context.Context, prID string, userID string) (bool, error) {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserReviewer")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, prID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Merge provides a mock function with given fields: ctx, prID
func (_m *PRRepository) Merge(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldReviewerID, newReviewerID
func (_m *PRRepository) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) error {
	ret := _m.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRRepository creates a new instance of PRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRRepository {
	mock := &PRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
