// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pr-reviewer-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PRUseCase is an autogenerated mock type for the PRUseCase type
type PRUseCase struct {
	mock.Mock
}

// CreatePR provides a mock function with given fields: ctx, prID, prName, authorID
func (_m *PRUseCase) CreatePR(ctx context.Context, prID string, prName string, authorID string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, prID, prName, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID, prName, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, prName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *PRUseCase) MergePR(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldReviewerID
func (_m *PRUseCase) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string) (*domain.PullRequest, string, error) {
	ret := _m.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *domain.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PullRequest, string, error)); ok {
		return rf(ctx, prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, prID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewPRUseCase creates a new instance of PRUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRUseCase {
	mock := &PRUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
