// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pr-reviewer-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TeamUseCase is an autogenerated mock type for the TeamUseCase type
type TeamUseCase struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: ctx, team
func (_m *TeamUseCase) CreateTeam(ctx context.Context, team *domain.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeactivateTeamUsers provides a mock function with given fields: ctx, teamName
func (_m *TeamUseCase) DeactivateTeamUsers(ctx context.Context, teamName string) (*domain.TeamDeactivationResult, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateTeamUsers")
	}

	var r0 *domain.TeamDeactivationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.TeamDeactivationResult, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TeamDeactivationResult); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TeamDeactivationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *TeamUseCase) GetTeam(ctx context.Context, teamName string) (*domain.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamUseCase creates a new instance of TeamUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamUseCase {
	mock := &TeamUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
