// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pr-reviewer-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// GetUserReviewPRs provides a mock function with given fields: ctx, userID
func (_m *UserUseCase) GetUserReviewPRs(ctx context.Context, userID string) ([]*domain.PullRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviewPRs")
	}

	var r0 []*domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.PullRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.PullRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserActive provides a mock function with given fields: ctx, userID, isActive
func (_m *UserUseCase) SetUserActive(ctx context.Context, userID string, isActive bool) (*domain.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetUserActive")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *domain.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
