// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package database

import (
	"context"
)

const deactivateTeamUsers = `-- name: DeactivateTeamUsers :exec
UPDATE users 
SET is_active = false 
WHERE team_name = $1
`

func (q *Queries) DeactivateTeamUsers(ctx context.Context, teamName string) error {
	_, err := q.db.ExecContext(ctx, deactivateTeamUsers, teamName)
	return err
}

const getActiveUsersFromTeam = `-- name: GetActiveUsersFromTeam :many
SELECT user_id, username, team_name, is_active
FROM users 
WHERE team_name = $1 AND is_active = true
`

func (q *Queries) GetActiveUsersFromTeam(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsersFromTeam, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTeams = `-- name: GetAllTeams :many
SELECT team_name FROM teams
`

func (q *Queries) GetAllTeams(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var team_name string
		if err := rows.Scan(&team_name); err != nil {
			return nil, err
		}
		items = append(items, team_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenPRsWithTeamReviewers = `-- name: GetOpenPRsWithTeamReviewers :many
SELECT DISTINCT pr.pull_request_id
FROM pull_requests pr
JOIN reviewers r ON pr.pull_request_id = r.pull_request_id
JOIN users u ON r.user_id = u.user_id
WHERE pr.status = 'OPEN' 
AND u.team_name = $1 
AND u.is_active = true
`

func (q *Queries) GetOpenPRsWithTeamReviewers(ctx context.Context, teamName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getOpenPRsWithTeamReviewers, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pull_request_id string
		if err := rows.Scan(&pull_request_id); err != nil {
			return nil, err
		}
		items = append(items, pull_request_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRAssignmentStats = `-- name: GetPRAssignmentStats :many
SELECT 
    pr.pull_request_id,
    pr.pull_request_name,
    COUNT(r.user_id) as reviewers_count
FROM pull_requests pr
LEFT JOIN reviewers r ON pr.pull_request_id = r.pull_request_id
GROUP BY pr.pull_request_id, pr.pull_request_name
ORDER BY reviewers_count DESC
`

type GetPRAssignmentStatsRow struct {
	PullRequestID   string
	PullRequestName string
	ReviewersCount  int64
}

func (q *Queries) GetPRAssignmentStats(ctx context.Context) ([]GetPRAssignmentStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPRAssignmentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPRAssignmentStatsRow
	for rows.Next() {
		var i GetPRAssignmentStatsRow
		if err := rows.Scan(&i.PullRequestID, &i.PullRequestName, &i.ReviewersCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRReviewersFromTeam = `-- name: GetPRReviewersFromTeam :many
SELECT r.user_id
FROM reviewers r
JOIN users u ON r.user_id = u.user_id
WHERE r.pull_request_id = $1 
AND u.team_name = $2 
AND u.is_active = true
`

type GetPRReviewersFromTeamParams struct {
	PullRequestID string
	TeamName      string
}

func (q *Queries) GetPRReviewersFromTeam(ctx context.Context, arg GetPRReviewersFromTeamParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPRReviewersFromTeam, arg.PullRequestID, arg.TeamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewStats = `-- name: GetReviewStats :many
SELECT u.user_id, u.username, COUNT(r.pull_request_id) as review_count
FROM users u
LEFT JOIN reviewers r ON u.user_id = r.user_id
GROUP BY u.user_id, u.username
ORDER BY review_count DESC
`

type GetReviewStatsRow struct {
	UserID      string
	Username    string
	ReviewCount int64
}

func (q *Queries) GetReviewStats(ctx context.Context) ([]GetReviewStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReviewStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewStatsRow
	for rows.Next() {
		var i GetReviewStatsRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.ReviewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
