// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type PullRequest struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
	Status          string
	MergedAt        sql.NullTime
}

type Reviewer struct {
	PullRequestID string
	UserID        string
}

type Team struct {
	TeamName string
}

type User struct {
	UserID   string
	Username string
	TeamName string
	IsActive bool
}
