// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package database

import (
	"context"
)

const createPullRequest = `-- name: CreatePullRequest :one
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id, status) 
VALUES ($1, $2, $3, 'OPEN') 
RETURNING pull_request_id, pull_request_name, author_id, status
`

type CreatePullRequestParams struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
}

type CreatePullRequestRow struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
	Status          string
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (CreatePullRequestRow, error) {
	row := q.db.QueryRowContext(ctx, createPullRequest, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	var i CreatePullRequestRow
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
	)
	return i, err
}

const getPullRequestByID = `-- name: GetPullRequestByID :one
SELECT pull_request_id, pull_request_name, author_id, status, merged_at 
FROM pull_requests 
WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequestByID(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestByID, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.MergedAt,
	)
	return i, err
}

const isPRMerged = `-- name: IsPRMerged :one
SELECT status = 'MERGED' as is_merged 
FROM pull_requests 
WHERE pull_request_id = $1
`

func (q *Queries) IsPRMerged(ctx context.Context, pullRequestID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPRMerged, pullRequestID)
	var is_merged bool
	err := row.Scan(&is_merged)
	return is_merged, err
}

const mergePullRequest = `-- name: MergePullRequest :one
UPDATE pull_requests 
SET status = 'MERGED', 
    merged_at = CASE 
        WHEN status = 'OPEN' THEN NOW()  
        ELSE merged_at                    
    END
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, merged_at
`

func (q *Queries) MergePullRequest(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, mergePullRequest, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.MergedAt,
	)
	return i, err
}

const pRExists = `-- name: PRExists :one
SELECT COUNT(*) FROM pull_requests WHERE pull_request_id = $1
`

func (q *Queries) PRExists(ctx context.Context, pullRequestID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, pRExists, pullRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
