// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviewers.sql

package database

import (
	"context"
)

const assignReviewer = `-- name: AssignReviewer :exec
INSERT INTO reviewers (pull_request_id, user_id) 
VALUES ($1, $2)
`

type AssignReviewerParams struct {
	PullRequestID string
	UserID        string
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) error {
	_, err := q.db.ExecContext(ctx, assignReviewer, arg.PullRequestID, arg.UserID)
	return err
}

const countReviewers = `-- name: CountReviewers :one
SELECT COUNT(*) FROM reviewers WHERE pull_request_id = $1
`

func (q *Queries) CountReviewers(ctx context.Context, pullRequestID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewers, pullRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPRReviewers = `-- name: GetPRReviewers :many
SELECT user_id FROM reviewers 
WHERE pull_request_id = $1
`

func (q *Queries) GetPRReviewers(ctx context.Context, pullRequestID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPRReviewers, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAssignedPRs = `-- name: GetUserAssignedPRs :many
SELECT pr.pull_request_id, pr.pull_request_name, pr.author_id, pr.status
FROM pull_requests pr
JOIN reviewers r ON pr.pull_request_id = r.pull_request_id
WHERE r.user_id = $1
`

type GetUserAssignedPRsRow struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
	Status          string
}

func (q *Queries) GetUserAssignedPRs(ctx context.Context, userID string) ([]GetUserAssignedPRsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAssignedPRs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAssignedPRsRow
	for rows.Next() {
		var i GetUserAssignedPRsRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserReviewer = `-- name: IsUserReviewer :one
SELECT COUNT(*) FROM reviewers 
WHERE pull_request_id = $1 AND user_id = $2
`

type IsUserReviewerParams struct {
	PullRequestID string
	UserID        string
}

func (q *Queries) IsUserReviewer(ctx context.Context, arg IsUserReviewerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserReviewer, arg.PullRequestID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeReviewer = `-- name: RemoveReviewer :exec
DELETE FROM reviewers 
WHERE pull_request_id = $1 AND user_id = $2
`

type RemoveReviewerParams struct {
	PullRequestID string
	UserID        string
}

func (q *Queries) RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error {
	_, err := q.db.ExecContext(ctx, removeReviewer, arg.PullRequestID, arg.UserID)
	return err
}
