// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_name) 
VALUES ($1) 
RETURNING team_name
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) (string, error) {
	row := q.db.QueryRowContext(ctx, createTeam, teamName)
	var team_name string
	err := row.Scan(&team_name)
	return team_name, err
}

const teamExists = `-- name: TeamExists :one
SELECT COUNT(*) FROM teams WHERE team_name = $1
`

func (q *Queries) TeamExists(ctx context.Context, teamName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, teamExists, teamName)
	var count int64
	err := row.Scan(&count)
	return count, err
}
